name: Building Project

on:
  push:
    branches: ["dev", "master", "staging"]
  pull_request:
    branches: ["dev", "master", "staging"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
      
      - run: flutter --version

      - name: Installing Dependencies
        run: flutter pub get

      - name: Analyze errors
        run: flutter analyze

      - name: Building assets
        run: flutter build bundle

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
      
      - run: flutter --version

      - name: Installing Dependencies
        run: flutter pub get

      - name: Analyze errors
        run: flutter analyze
        
      - name: Building assets
        run: flutter build bundle

      - name: Building App
        run: flutter build ios --release --no-codesign
