export enum MODEL {
  Patient = 'Patient',
  Admin = 'Admin',
  Post = 'Post',
  Therapist = 'Therapist',
  Credential = 'Credential',
  PostPhoto = 'PostPhoto',
  Activities = 'Activities',
  ActivityImages = 'ActivityImages',
  PatientComment = 'PatientComment',
  SavePost = 'SavePost',
  StressMonitor = 'StressMonitor',
  MindCheckup = 'MindCheckup',
  TherapistApplication = 'TherapistApplication',
  TherapistApplicationPhoto = 'TherapistApplicationPhoto',
}
